language: java
jdk:
  - oraclejdk8

before_install:
  - sudo apt-get update -qq
  - sudo apt-get install -y llvm

script:
  - mvn compile
  - git diff --exit-code > /dev/null
  - mvn package
  - java -jar target/moco-0.7.jar --help
